// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $film_id_ from "./routes/film/[id].tsx";
import * as $films from "./routes/films.tsx";
import * as $index from "./routes/index.tsx";
import * as $project_name_ from "./routes/project/[name].tsx";
import * as $projects from "./routes/projects.tsx";
import * as $FilmsPage from "./islands/FilmsPage.tsx";
import * as $ModalAddFilm from "./islands/ModalAddFilm.tsx";
import * as $ModalDeleteFilm from "./islands/ModalDeleteFilm.tsx";
import * as $ModalDeleteProject from "./islands/ModalDeleteProject.tsx";
import * as $ModalSelectProject from "./islands/ModalSelectProject.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/film/[id].tsx": $film_id_,
    "./routes/films.tsx": $films,
    "./routes/index.tsx": $index,
    "./routes/project/[name].tsx": $project_name_,
    "./routes/projects.tsx": $projects,
  },
  islands: {
    "./islands/FilmsPage.tsx": $FilmsPage,
    "./islands/ModalAddFilm.tsx": $ModalAddFilm,
    "./islands/ModalDeleteFilm.tsx": $ModalDeleteFilm,
    "./islands/ModalDeleteProject.tsx": $ModalDeleteProject,
    "./islands/ModalSelectProject.tsx": $ModalSelectProject,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
